#.https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(release)_$(projectCode)_$(sprint)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)




variables:
 # - group: Task_git_task_ab
  - template: templates/template1/variables.yml



stages:

- stage: Arithmetic_operations_stage
  displayName: ' Arithmetic operations stage '
  
    jobs:
    
      - job: Java_attaching_artifact_to_pipeline
    dependsOn: sum_of_parameters
    #condition: failed() 
    # this job will only run if sum_of_parameters fails
    displayName: ' 8_Java attaching artifact to pipelines '
    
    
    steps:
     - task: Maven@3
       inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
     - task: CopyFiles@2
         inputs:
         Contents: '**/*war'
        TargetFolder: '$(build.artifactstagingdirectory)'
     - task: PublishBuildArtifacts@1
      inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'droppp'
      publishLocation: 'Container'
